# build docker an deploy to github regestry

name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: "ghcr.io/${{ github.repository }}:latest"
      - name: Inspect
        run: |
          docker buildx imagetools inspect "ghcr.io/${{ github.repository }}:latest"
